### ISSUE TITLE
Installation in python

### ISSUE THREAD

**Issue by prabhat1221** [herbertbay/SURF#2]
How can we use this algo in python? #1

**Comment by herbertbay** [comment]
Hi, check out this book. https://www.amazon.com/Programming-Computer-Vision-Python-algorithms/dp/1449316549 <https://www.amazon.com/Programming-Computer-Vision-Python-algorithms/dp/1449316549>

**Comment by brean** [comment]
It's also part of OpenCV, here's a quick tutorial: https://docs.opencv.org/master/df/dd2/tutorial_py_surf_intro.html

**Comment by prabhat1221** [comment]
Thank you
